version: '3'
networks:
  test-network:
    driver: bridge
services:
  mongodb:
    image: mongo:latest
    environment:
      - 'MONGO_INITDB_DATABASE=forex'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
    ports:
      - '27017:27017'
    networks:
      test-network:
    hostname: mongodb
    healthcheck:
      test: ["CMD", "mongosh"]

  forex-api:
    depends_on:
      mongodb:
        condition: service_healthy
    image: 'forex-api:latest'
    ports:
      - '8080:8080'
    networks:
      test-network: