spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/
      database: forex

forex:
  api:
#    url: "https://openapi.taifex.com.tw/v1/DailyForeignExchangeRates"
    url: "http://localhost:8088/v1/DailyForeignExchangeRates"
  # 每3秒
  cron: "*/3 * * * * *"