spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/?connectTimeoutMS=2000
      database: forex

forex:
  api:
    url: "https://openapi.taifex.com.tw/v1/DailyForeignExchangeRates"
#  cron: "*/3 * * * * *"
  cron: "0 0 18 1/1 * ?"